-- DDL generated by Postico 2.0
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE gotitcards.categories (
    id text PRIMARY KEY,
    name text,
    description text,
    user_id text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX categories_pkey ON gotitcards.categories(id text_ops);
