-- DDL generated by Postico 2.0
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE gotitcards.users (
    email text PRIMARY KEY,
    name text,
    password text,
    last_login text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX users_pkey ON gotitcards.users(email text_ops);
